// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240227072959_v1_create_table_Products")]
    partial class v1_create_table_Products
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(4);

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(3);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(9);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DateTime")
                        .HasColumnOrder(8);

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnOrder(7);

                    b.Property<string>("Manufacture")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(4);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnOrder(6);

                    b.Property<string>("ProductGUID")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("ProductName")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnOrder(3);

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnOrder(5);

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(11);

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DateTime")
                        .HasColumnOrder(10);

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
